auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095

common:
  instance_addr: 0.0.0.0
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
#    s3:
#      endpoint: minio:9000
#      bucketnames: loki-bucket # name of the bucket created in MinIO
#      insecure: true
#      access_key_id: ${MINIO_USER}
#      secret_access_key: ${MINIO_PASSWORD}
#      s3forcepathstyle: true # needed for MinIO
  replication_factor: 1 # single node setup
  ring:
    kvstore:
      store: inmemory

ingester:
  wal:
    enabled: true
    dir: /loki/wal
  chunk_encoding: snappy
  chunk_idle_period: 1h
  chunk_target_size: 1536000
  max_chunk_age: 2h

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h  # 7 days
  volume_enabled: true

  # Ingestion limits
  ingestion_rate_mb: 20
  ingestion_burst_size_mb: 30

  # Per-stream protections
  per_stream_rate_limit: "3MB"
  per_stream_rate_limit_burst: "10MB"

  # Query limits / parallelism
  max_query_parallelism: 8 # Set max_query_parallelism to CPU cores (or lower).
  split_queries_by_interval: 15m
  query_timeout: 120s # reduce to limit runaway queries
  
  # Protections to avoid very large/expensive queries
  max_entries_limit_per_query: 50000

  allow_structured_metadata: true

schema_config:
  configs:
    - from: 2024-01-01
      store: tsdb
      object_store: filesystem # or s3
      schema: v13
      index:
        prefix: index_
        period: 24h

compactor:
  working_directory: /loki/compactor

ruler:
  storage:
    type: local # or s3
    local:
      directory: /loki/rules
#    s3:
#      endpoint: minio:9000
#      bucketnames: loki-rules # name of the bucket created in MinIO
#      insecure: true
#      access_key_id: ${MINIO_USER}
#      secret_access_key: ${MINIO_PASSWORD}
#      s3forcepathstyle: true # needed for MinIO

#TODO: Add alertmanager config if needed. 
#TODO: Add Prometheus alerts for /loki disk usage, WAL size, and high query latencies.