global:
  scrape_interval: 5s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "otel-collector"
    static_configs:
      - targets: [ "otel-collector:8890" ]
        labels:
          service: "otel-collector"
          environment: "local"